import type { NextPage } from 'next'
import Head from 'next/head'
import Link from 'next/link'

const Home: NextPage = () => {

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
          <Link href={"/adminPanel/dashboard"} passHref>
              <button className="btn btn-primary">صفحه داشبورد</button>
          </Link>
      </main>

      <footer>

      </footer>
    </div>
  )
}

export default Home
